services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: contact_db
      POSTGRES_USER: contact_user
      POSTGRES_PASSWORD: contact_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
